# Site settings
title: Alex Flint
email: me@alexf.ca
formspree_code: xdopgrja
url: https://alexf.ca
description: "I am a Software Developer specializing in Ruby on Rails, NationBuilder and Shopify."
keywords: "software developer, nationbuilder, shopify, ruby on rails"
skills: "Software Developer - Certified NationBuilder Architect - Technologist"
meta_author: Alex Flint

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 71cae8 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: e88f71 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Alex Flint
  location: 
  social: 
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title:
    url:

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Credits content
credits: 'I support open source software, like this theme created by <a class="text-dark" href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
